version: "2.2"

services:
  keycloak_test:
    container_name: keycloak_test
    build: .
    image: keycloak_test
    hostname: keycloak-test.stackhpc.com
    ports:
      - 8480:8480

  freeipa:
    container_name: freeipa
    image: freeipa/freeipa-server:centos-7
    hostname: freeipa.stackhpc.com
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ipa_data:/data:Z
    tmpfs:
      - /run
      - /tmp

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    hostname: keycloak.stackhpc.com
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080

volumes:
    ipa_data:
